// Mirrors swify-server/src/constants/notification.types.js
export const NOTIFICATION_TYPES = {
  PAYMENT_SENT: "PAYMENT_SENT",
  PAYMENT_RECEIVED: "PAYMENT_RECEIVED",
  KYC_SUBMITTED: "KYC_SUBMITTED",
  KYC_APPROVED: "KYC_APPROVED",
  KYC_REJECTED: "KYC_REJECTED",
  MPIN_CREATED: "MPIN_CREATED",
  MPIN_CHANGED: "MPIN_CHANGED",
  SYSTEM: "SYSTEM",
};
