import { useState, useEffect, useRef, useCallback } from "react";
import { useNavigate, Link } from "react-router-dom";
import jsQR from "jsqr";
import { ArrowLeft, X, Check, Zap } from "lucide-react";
import { API_BASE_URL } from "../config";
 
const PIN_LENGTH = 6;
 
async function safeFetchJson(url, options) {
  const res = await fetch(url, { credentials: "include", ...options });
  const rawText = await res.text();
  let data;
  try {
    data = JSON.parse(rawText);
  } catch {
    throw new Error("Server didn't return valid JSON. Check the backend is running.");
  }
  if (!res.ok || !data.success) {
    throw new Error(data.message || "Something went wrong.");
  }
  return data;
}
 
function formatAmount(n) {
  return new Intl.NumberFormat("en-IN", { maximumFractionDigits: 2 }).format(n || 0);
}
 
function initialsOf(name) {
  return (
    (name || "")
      .trim()
      .split(" ")
      .filter(Boolean)
      .slice(0, 2)
      .map((n) => n[0]?.toUpperCase())
      .join("") || "?"
  );
}
 
export default function SwifyScan() {
  const navigate = useNavigate();
 
  // stage: "scanning" | "amount" | "mpin" | "success"
  const [stage, setStage] = useState("scanning");
  const [errorMsg, setErrorMsg] = useState("");
  const [submitting, setSubmitting] = useState(false);
 
  const [cameraError, setCameraError] = useState("");
  const [scannedQrData, setScannedQrData] = useState(null); // raw JSON string from QR
  const [resolvedReceiver, setResolvedReceiver] = useState(null); // { displayName, payAddress, avatar }
 
  const [amount, setAmount] = useState("");
  const [note, setNote] = useState("");
  const [pin, setPin] = useState("");
 
  const [transferResult, setTransferResult] = useState(null);
 
  const videoRef = useRef(null);
  const canvasRef = useRef(document.createElement("canvas"));
  const streamRef = useRef(null);
  const rafRef = useRef(null);
  const scanningLockRef = useRef(false);
 
  // ---------- Camera + scan loop ----------
  const stopCamera = useCallback(() => {
    if (rafRef.current) cancelAnimationFrame(rafRef.current);
    if (streamRef.current) {
      streamRef.current.getTracks().forEach((t) => t.stop());
      streamRef.current = null;
    }
  }, []);
 
  const tick = useCallback(() => {
    const video = videoRef.current;
    const canvas = canvasRef.current;
 
    if (video && video.readyState === video.HAVE_ENOUGH_DATA && !scanningLockRef.current) {
      canvas.width = video.videoWidth;
      canvas.height = video.videoHeight;
      const ctx = canvas.getContext("2d");
      ctx.drawImage(video, 0, 0, canvas.width, canvas.height);
      const imageData = ctx.getImageData(0, 0, canvas.width, canvas.height);
      const code = jsQR(imageData.data, imageData.width, imageData.height);
 
      if (code?.data) {
        scanningLockRef.current = true;
        handleScanResult(code.data);
        return; // stop the loop once we have a hit
      }
    }
    rafRef.current = requestAnimationFrame(tick);
  }, []);
 
  useEffect(() => {
    if (stage !== "scanning") return;
 
    let cancelled = false;
    scanningLockRef.current = false;
    setCameraError("");
 
    navigator.mediaDevices
      .getUserMedia({ video: { facingMode: "environment" } })
      .then((stream) => {
        if (cancelled) {
          stream.getTracks().forEach((t) => t.stop());
          return;
        }
        streamRef.current = stream;
        if (videoRef.current) {
          videoRef.current.srcObject = stream;
          videoRef.current.play();
        }
        rafRef.current = requestAnimationFrame(tick);
      })
      .catch(() => {
        setCameraError(
          "Couldn't access your camera. Check permissions, or use manual entry below."
        );
      });
 
    return () => {
      cancelled = true;
      stopCamera();
    };
  }, [stage, tick, stopCamera]);
 
  const handleScanResult = async (data) => {
    stopCamera();
    setErrorMsg("");
    setScannedQrData(data);
 
    // Pull amount/note straight from the raw QR payload if this is a
    // "Request money" QR (generated by SwifyRequest.jsx) — the backend's
    // /transfer/scan only validates & returns the recipient's identity,
    // not any requested amount, so that part is read client-side.
    let prefillAmount = "";
    let prefillNote = "";
    try {
      const parsed = JSON.parse(data);
      if (parsed.type === "REQUEST") {
        if (parsed.amount) prefillAmount = String(parsed.amount);
        if (parsed.note) prefillNote = parsed.note;
      }
    } catch {
      // not JSON / not a request QR — ignore, plain contact QR
    }
 
    try {
      const res = await safeFetchJson(`${API_BASE_URL}/transfer/scan`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ qrData: data }),
      });
      setResolvedReceiver(res.data);
      if (prefillAmount) setAmount(prefillAmount);
      if (prefillNote) setNote(prefillNote);
      setStage("amount");
    } catch (err) {
      setErrorMsg(err.message);
      // Give the user a moment to read the error, then resume scanning
      setTimeout(() => {
        scanningLockRef.current = false;
        setErrorMsg("");
        if (stage === "scanning") rafRef.current = requestAnimationFrame(tick);
      }, 2000);
    }
  };
 
  // ---------- Amount stage ----------
  const goToMpin = () => {
    setErrorMsg("");
    const numericAmount = Number(amount);
    if (!numericAmount || numericAmount <= 0) {
      setErrorMsg("Enter an amount greater than zero.");
      return;
    }
    setPin("");
    setStage("mpin");
  };
 
  // ---------- MPIN stage ----------
  const handleKeyPress = (digit) => {
    if (submitting || pin.length >= PIN_LENGTH) return;
    setErrorMsg("");
    setPin(pin + digit);
  };
 
  const handleBackspace = () => {
    if (submitting) return;
    setErrorMsg("");
    setPin(pin.slice(0, -1));
  };
 
  useEffect(() => {
    if (pin.length === PIN_LENGTH && stage === "mpin") {
      submitPayment();
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [pin]);
 
  const submitPayment = async () => {
    setSubmitting(true);
    setErrorMsg("");
    try {
      const mpinRes = await safeFetchJson(`${API_BASE_URL}/mpin/verify`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ mpin: pin }),
      });
 
      const res = await fetch(`${API_BASE_URL}/transfer/qr`, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          "x-payment-authorisation": mpinRes.paymentToken,
        },
        credentials: "include",
        body: JSON.stringify({
          qrData: scannedQrData,
          amount: Number(amount),
          note,
        }),
      });
 
      const rawText = await res.text();
      let data;
      try {
        data = JSON.parse(rawText);
      } catch {
        throw new Error("Server didn't return valid JSON. Check the backend is running.");
      }
      if (!res.ok || !data.success) {
        throw new Error(data.message || "Payment failed. Please try again.");
      }
 
      setTransferResult(data.data);
      setStage("success");
    } catch (err) {
      setErrorMsg(err.message);
      setPin("");
    } finally {
      setSubmitting(false);
    }
  };
 
  // ---------- SUCCESS ----------
  if (stage === "success") {
    return (
      <div className="min-h-screen w-full flex flex-col items-center justify-center bg-black text-white px-6 text-center">
        <div className="w-20 h-20 rounded-full bg-[#5ee6a8] flex items-center justify-center mb-6">
          <Check size={36} className="text-black" />
        </div>
        <h1 className="text-2xl font-extrabold">Payment sent</h1>
        <p className="text-gray-400 text-sm mt-2">
          ₹{formatAmount(amount)} paid to{" "}
          {resolvedReceiver?.displayName || resolvedReceiver?.payAddress}
        </p>
        {transferResult?.reference && (
          <p className="text-gray-600 text-xs mt-1 font-mono">
            Ref: {transferResult.reference}
          </p>
        )}
        <button
          onClick={() => navigate("/home")}
          className="w-full max-w-xs bg-white text-black text-base font-semibold rounded-full py-3 mt-10 hover:bg-gray-200 transition-colors duration-200"
        >
          Back to Home
        </button>
      </div>
    );
  }
 
  // ---------- MPIN ----------
  if (stage === "mpin") {
    return (
      <div className="min-h-screen w-full flex flex-col items-center justify-between bg-black text-white px-6 py-12">
        <div className="w-full flex items-center">
          <button onClick={() => setStage("amount")} className="text-gray-400 hover:text-white">
            <ArrowLeft size={22} />
          </button>
        </div>
 
        <div className="text-center">
          <h1 className="text-2xl font-extrabold">Enter your MPIN</h1>
          <p className="mt-2 text-gray-400 text-sm">
            Confirm paying ₹{formatAmount(amount)} to{" "}
            {resolvedReceiver?.displayName || resolvedReceiver?.payAddress}
          </p>
        </div>
 
        <div className="flex flex-col items-center gap-4">
          <div className="flex gap-4">
            {Array.from({ length: PIN_LENGTH }).map((_, i) => (
              <div
                key={i}
                className={`w-4 h-4 rounded-full border-2 transition-colors duration-150 ${
                  i < pin.length ? "bg-white border-white" : "bg-transparent border-gray-600"
                }`}
              />
            ))}
          </div>
          <p className="text-red-400 text-sm h-5">{errorMsg}</p>
        </div>
 
        <div className="grid grid-cols-3 gap-5 w-full max-w-xs">
          {["1", "2", "3", "4", "5", "6", "7", "8", "9"].map((digit) => (
            <button
              key={digit}
              type="button"
              onClick={() => handleKeyPress(digit)}
              disabled={submitting}
              className="aspect-square rounded-full bg-[#111111] border border-[#222] text-2xl font-semibold flex items-center justify-center hover:border-white active:scale-95 transition-all duration-150 disabled:opacity-50"
            >
              {digit}
            </button>
          ))}
          <div />
          <button
            type="button"
            onClick={() => handleKeyPress("0")}
            disabled={submitting}
            className="aspect-square rounded-full bg-[#111111] border border-[#222] text-2xl font-semibold flex items-center justify-center hover:border-white active:scale-95 transition-all duration-150 disabled:opacity-50"
          >
            0
          </button>
          <button
            type="button"
            onClick={handleBackspace}
            disabled={submitting}
            className="aspect-square rounded-full flex items-center justify-center text-gray-400 hover:text-white active:scale-95 transition-all duration-150 disabled:opacity-50"
          >
            ⌫
          </button>
        </div>
      </div>
    );
  }
 
  // ---------- AMOUNT ----------
  if (stage === "amount") {
    const numericAmount = Number(amount) || 0;
    const canContinue = numericAmount > 0;
 
    return (
      <div className="min-h-screen w-full flex flex-col bg-black text-white">
        <div className="flex items-center justify-between px-5 pt-6 pb-5">
          <button
            onClick={() => {
              setStage("scanning");
              setResolvedReceiver(null);
              setAmount("");
              setNote("");
            }}
            className="w-11 h-11 rounded-2xl bg-[#161616] flex items-center justify-center hover:bg-[#222] transition-colors duration-200"
          >
            <ArrowLeft size={18} />
          </button>
          <h1 className="text-lg font-bold">Pay via QR</h1>
          <Link
            to="/home"
            className="w-11 h-11 rounded-2xl bg-[#161616] flex items-center justify-center hover:bg-[#222] transition-colors duration-200"
          >
            <X size={18} />
          </Link>
        </div>
 
        <div className="h-px bg-[#1a1a1a]" />
 
        <div className="flex items-center gap-3 px-5 py-5">
          <div className="w-14 h-14 rounded-full bg-[#1a1a1a] flex items-center justify-center overflow-hidden shrink-0">
            {resolvedReceiver?.avatar ? (
              <img
                src={resolvedReceiver.avatar}
                alt=""
                className="w-full h-full object-cover"
              />
            ) : (
              <span className="text-base font-bold">
                {initialsOf(resolvedReceiver?.displayName)}
              </span>
            )}
          </div>
          <div>
            <p className="text-lg font-bold leading-tight">
              {resolvedReceiver?.displayName || "Recipient"}
            </p>
            <p className="text-sm text-gray-500 font-mono mt-0.5">
              {resolvedReceiver?.payAddress}
            </p>
          </div>
        </div>
 
        <div className="h-px bg-[#1a1a1a]" />
 
        <div className="flex-1 flex flex-col items-center justify-center px-5 min-h-[200px]">
          <div className="flex items-center gap-2">
            <span className={`text-3xl ${amount ? "text-gray-500" : "text-gray-700"}`}>₹</span>
            <span
              className={`text-7xl font-bold font-mono tabular-nums ${
                amount ? "text-white" : "text-gray-700"
              }`}
            >
              {amount || "0"}
            </span>
          </div>
        </div>
 
        <div className="px-5 pb-2">
          <div className="flex items-center gap-3 bg-[#111111] rounded-full px-5 py-4">
            <input
              type="text"
              placeholder="What's it for? (optional)"
              maxLength={100}
              value={note}
              onChange={(e) => setNote(e.target.value)}
              className="w-full bg-transparent text-white text-base outline-none placeholder:text-gray-500"
            />
          </div>
        </div>
 
        {errorMsg && <p className="text-red-400 text-sm text-center mt-3 px-5">{errorMsg}</p>}
        {!errorMsg && <div className="mt-4" />}
 
        <div className="grid grid-cols-3 border-t border-[#1a1a1a]">
          {["1", "2", "3", "4", "5", "6", "7", "8", "9", ".", "0", "back"].map((key, i) => (
            <button
              key={i}
              onClick={() => {
                setErrorMsg("");
                if (key === "back") {
                  setAmount(amount.slice(0, -1));
                } else if (key === ".") {
                  if (!amount.includes(".")) setAmount((amount || "0") + ".");
                } else if (amount === "0") {
                  setAmount(key);
                } else {
                  setAmount(amount + key);
                }
              }}
              className={`h-[70px] flex items-center justify-center text-2xl font-semibold border-[#1a1a1a] hover:bg-[#0d0d0d] active:bg-[#151515] transition-colors duration-150 ${
                (i + 1) % 3 !== 0 ? "border-r" : ""
              } ${i < 9 ? "border-b" : ""}`}
            >
              {key === "back" ? "⌫" : key}
            </button>
          ))}
        </div>
 
        <button
          onClick={goToMpin}
          disabled={!canContinue}
          className={`w-full py-5 text-lg font-semibold transition-colors duration-200 ${
            canContinue
              ? "bg-white text-black hover:bg-gray-200"
              : "bg-[#161616] text-gray-600 cursor-not-allowed"
          }`}
        >
          Pay
        </button>
      </div>
    );
  }
 
  // ---------- SCANNING (default) ----------
  return (
    <div className="min-h-screen w-full bg-black text-white relative overflow-hidden">
      <video
        ref={videoRef}
        playsInline
        muted
        className="absolute inset-0 w-full h-full object-cover"
      />
 
      {/* Dark overlay with cutout */}
      <div className="absolute inset-0 bg-black/50" />
 
      {/* Header */}
      <div className="absolute top-0 left-0 right-0 flex items-center justify-between px-5 pt-6 z-10">
        <Link
          to="/home"
          className="w-11 h-11 rounded-2xl bg-black/60 flex items-center justify-center hover:bg-black/80 transition-colors duration-200"
        >
          <ArrowLeft size={18} />
        </Link>
        <h1 className="text-lg font-bold">Scan to pay</h1>
        <div className="w-11 h-11 rounded-2xl bg-black/60 flex items-center justify-center opacity-40">
          <Zap size={18} />
        </div>
      </div>
 
      {/* Scan frame */}
      <div className="absolute inset-0 flex items-center justify-center z-10">
        <div className="w-64 h-64 relative">
          <div className="absolute top-0 left-0 w-10 h-10 border-t-4 border-l-4 border-white rounded-tl-2xl" />
          <div className="absolute top-0 right-0 w-10 h-10 border-t-4 border-r-4 border-white rounded-tr-2xl" />
          <div className="absolute bottom-0 left-0 w-10 h-10 border-b-4 border-l-4 border-white rounded-bl-2xl" />
          <div className="absolute bottom-0 right-0 w-10 h-10 border-b-4 border-r-4 border-white rounded-br-2xl" />
        </div>
      </div>
 
      {/* Status text */}
      <div className="absolute bottom-24 left-0 right-0 flex flex-col items-center px-8 z-10">
        {errorMsg ? (
          <p className="text-red-400 text-sm text-center bg-black/60 px-4 py-2 rounded-full">
            {errorMsg}
          </p>
        ) : cameraError ? (
          <p className="text-red-400 text-sm text-center bg-black/60 px-4 py-2 rounded-full">
            {cameraError}
          </p>
        ) : (
          <p className="text-gray-300 text-sm text-center bg-black/60 px-4 py-2 rounded-full">
            Point your camera at a Swify QR code
          </p>
        )}
      </div>
    </div>
  );
}